### ISSUE TITLE
Add mermaid-js rendering capabilities

### ISSUE THREAD

**Issue by TheLazzziest** [structurizr/structurizr#101]
It would be really great if Structurizr could render mermaid-js code embedded into documentation. 

So, I could add the following code:

```
'''mermaid
sequenceDiagram
    participant dotcom
    participant iframe
    participant viewscreen
    dotcom->>iframe: loads html w/ iframe url
    iframe->>viewscreen: request template
    viewscreen->>iframe: html & javascript
    iframe->>dotcom: iframe ready
    dotcom->>iframe: set mermaid data on iframe
    iframe->>iframe: render mermaid
'''
```

which would turn into the following:

```mermaid
sequenceDiagram
    participant dotcom
    participant iframe
    participant viewscreen
    dotcom->>iframe: loads html w/ iframe url
    iframe->>viewscreen: request template
    viewscreen->>iframe: html & javascript
    iframe->>dotcom: iframe ready
    dotcom->>iframe: set mermaid data on iframe
    iframe->>iframe: render mermaid
```

**Comment by simonbrowndotje** [comment]
Mermaid isn't supported out of the box, but you could write a plugin to convert Mermaid definitions in Markdown/AsciiDoc to an image. Here's an example [PlantUML plugin](https://github.com/structurizr/dsl-plugins/tree/main/src/main/java/com/structurizr/dsl/plugins/plantuml) to get you started.

**Comment by simonbrowndotje** [comment]
I had most of the code already written elsewhere, so here's a [Mermaid plugin](https://github.com/structurizr/dsl-plugins/tree/main/src/main/java/com/structurizr/dsl/plugins/mermaid).

To build it, clone the repo and run `.gradlew clean build` ... the resulting JAR file will be located in `build/libs`, which can be placed in a directory named `plugins` next to your `workspace.dsl` file. You can then use your plugin from the DSL via the `!plugin` keyword as detailed in the [README.md](https://github.com/structurizr/dsl-plugins/tree/main/src/main/java/com/structurizr/dsl/plugins/mermaid#usage).

**Comment by simonbrowndotje** [comment]
I've added an example at https://github.com/structurizr/examples/tree/main/dsl/plantuml-and-mermaid
