### ISSUE TITLE
Sort decisions list 

### ISSUE THREAD

**Issue by ksciana** [structurizr/structurizr#104]
Currently, the decision list is enumerated automatically, but displayed in the list in sort order as plain text.

The expected behavior is to sort by number. 
Grouping by date / year is correct, but it looks bad inside a group.

File names:
![image](https://user-images.githubusercontent.com/1391147/183859548-9f93fe10-37dc-4260-bb59-ad1afc2ed438.png)
 
 Generated view:
 
![image](https://user-images.githubusercontent.com/1391147/183859710-f2ea6a9b-0cd8-4e98-b3ae-ec69d94a4e5b.png)

**Comment by simonbrowndotje** [comment]
Decisions should be sorted by date, descending, rather than decision ID.
