### ISSUE TITLE
Web API for adding and removing users from workspaces 

### ISSUE THREAD

**Issue by yevheniisemenov** [structurizr/structurizr#107]
Hello! Since the cloud version does not support login via Google, we should add and remove users manually. It would be great if you add Web API for adding and removing users so we could automate these actions.

**Comment by simonbrowndotje** [comment]
It depends how you're authoring your workspace, but you can specify the set of read-only/read-write users. For example, with the DSL -> https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#users

**Comment by yevheniisemenov** [comment]
We manage users via web UI. Currently, we have automation for onboarding/offboarding in the organization. This automation uses REST API for different services that we use in the organization. It would be good if we could add Structurizr to this automation. I'm not sure DSL is applicable for this use case.

**Comment by simonbrowndotje** [comment]
Are you using the DSL, or one of the code-based libraries?

**Comment by yevheniisemenov** [comment]
Sorry for the late reply. We are using DSL.

**Comment by simonbrowndotje** [comment]
In that case, my recommendation would be to write a [DSL plugin](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#plugins) that figures out who has access to the workspace, and adds this set of users into the workspace; for example:

```
workspace.getConfiguration().addUser("somebody@example.com", Role.ReadWrite);
```

**Comment by yevheniisemenov** [comment]
Thanks, I will try this option.
