### ISSUE TITLE
Can't agree to EULA using Lite

### ISSUE THREAD

**Issue by markj-** [structurizr/structurizr#108]
Hello!

I'm using docker.io/structurizr/lite `ecb6bcfbe34c` and whenever I click the "Accept" button I am redirected back to the same page. This happens in Chrome, Firefox and Safari.

The request url is http://localhost:8080/eula and the response headers are:

```
HTTP/1.1 302
Referrer-Policy: strict-origin-when-cross-origin
X-Frame-Options: deny
Location: /
Content-Language: en-GB
Content-Length: 0
Date: Fri, 12 Aug 2022 07:12:58 GMT
Keep-Alive: timeout=20
Connection: keep-alive
```

In the stdout I see the following error:

```
[ERROR] 2022-08-12 07:12:58.573 [http-nio-8080-exec-5] Eula - java.io.FileNotFoundException: /usr/local/structurizr/.structurizr/eula.properties (No such file or directory)
```

Any help would be much appreciated.

**Comment by simonbrowndotje** [comment]
My first suggestion would be to check permissions ... it sounds like the Docker container can't write to the folder you've provided as a volume mount.
