### ISSUE TITLE
Add version history of docker image of structurizr-lite

### ISSUE THREAD

**Issue by cgi** [structurizr/structurizr#110]
It would be very cool to have some version history of structurizr-lite docker images to have option to stick to some fixed version for some time - for now - every rebuild of structurizr-lite based container - is out of control as base image can change at any moment...

**Comment by simonbrowndotje** [comment]
Images are now tagged with the build number -> https://hub.docker.com/r/structurizr/lite/tags

**Comment by cgi** [comment]
thanks! great!
