### ISSUE TITLE
Relationship to container is included in Context view

### ISSUE THREAD

**Issue by Dawnsurfer** [structurizr/structurizr#111]
If couplings to containers inside a software system is defined before the couplings to the software system, the first defined container coupling will be included in the context diagram for the software system. By defining the system couplings first and then the container couplings, the container coupling is not part of the context diagram, as expected.

Using Structurizr Lite, Build 2757 on Docker

Example to recreate the behavior:

```
workspace test {
    !identifiers hierarchical

    model {
        dude = person "Test Person"
        
        testSystem = softwareSystem "Test System" {
            cont1 = container "A" {
            }
            cont2 = container "B" {

            }
        }

        # By defining the coupling from dude to testSystem here, everything is as expected
        # dude -> testSystem "Uses"

        dude -> testSystem.cont1 "Really using this"
        dude -> testSystem.cont2 "Also using this"

        # By defining the coupling from dude to testSystem here, the first defined coupling to a container is included in the system context
        dude -> testSystem "Uses"
    }

    views {
        systemContext testSystem "Diagram1" {
            include *
            autoLayout
        }

        container testSystem "Diagram2" {
            include *
            autoLayout
        }
    }
}

```

**Comment by simonbrowndotje** [comment]
This sounds like the result of the implied relationships feature; see https://github.com/structurizr/dsl/tree/master/docs/cookbook/implied-relationships for more.

**Comment by Dawnsurfer** [comment]
Thanks. Setting impliedRelationships to false solved the issue. Many thanks for quick response and solution.
