### ISSUE TITLE
Can't edit diagrams

### ISSUE THREAD

**Issue by bnheise** [structurizr/structurizr#113]
If I load the diagram editor, I cannot make any changes. Everything is locked in places and I can move nothing when I click and drag. All there is is a message saying that I can't edit because auto layout is turned on, but there is no button to disable auto layout. The autolayout for my diagram is terrible. I definitely can't show it to anyone because it's too hard to read, but I can't change the layout either.
![スクリーンショット 2022-08-19 14 37 46](https://user-images.githubusercontent.com/92563897/185550505-03303700-fb94-41da-9d95-575712f3e057.png)
.

**Comment by simonbrowndotje** [comment]
Auto-layout being on/off is controlled by your workspace source (DSL, Java code, .NET code, etc). If you're using the DSL and letting the DSL parser automatically create your views, these have auto-layout on by default; see [Convention over configuration, useful defaults](https://github.com/structurizr/dsl#convention-over-configuration-useful-defaults) for more. You can either manually define your views without auto-layout, or use a script to disable auto-layout (see [Create the default views, without automatic layout](https://github.com/structurizr/dsl/tree/master/docs/cookbook/scripts#create-the-default-views-without-automatic-layout)).

**Comment by bnheise** [comment]
Thanks for your help! I'd like to provide some feedback to help other users in this situation. When a new user comes to the site, they are apt to simply copy some of the examples so they can experiment with them. The examples typically have autolayout turned on. When a user checks any documentation or videos online, they see that users should be able to drag around elements to edit the layout, but they will find that they can't. When they check to find why, they will likely not find an answer (as was my situation). I'd suggest finding a way to override the autolayout feature through the UI. After all, it is the UI telling the user that they can't edit it; the user expects therefore that there would be a button to disable autolayout. One wouldn't think to look through the code to find that.

**Comment by simonbrowndotje** [comment]
I've added a note to the DSL documentation about disabling automatic layout (https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#autoLayout), and the auto-layout help page is now linked from the `diagram not editable; automatic layout enabled` message. 

> I'd suggest finding a way to override the autolayout feature through the UI.

Unfortunately this isn't possible, because the Structurizr UI doesn't know whether you've authored your workspace via the DSL or one of the code-based client libraries.

> One wouldn't think to look through the code to find that.

This is a "diagrams as code" solution though. 🙂
