### ISSUE TITLE
Keyboard shortcut for "Go back to previous diagram" (function Structurizr.diagram.navigateToPreviousView())?

### ISSUE THREAD

**Issue by StanleyP** [structurizr/structurizr#114]
Hello,

I would like to ask if there is keyboard shortcut for "Go back to previous diagram" functionality, which is available in web UI via dedicated button? (This button calls function Structurizr.diagram.navigateToPreviousView().)

If I click through from System Landscape to System Context and then press the "Go back to previous diagram", it correctly returns to System Landscape diagram. But when I use previous diagram keyboard shortcut (up or left arraw according to documentation) the view switches to previous diagram from the diagram list on the left.

It would be very handy especially in presentation mode.

**Comment by simonbrowndotje** [comment]
The keyboard shortcut for your web browser's back button should work.

**Comment by StanleyP** [comment]
Thanks for quick answer, but unfortunately I tried it in latest firefox and chrome which have "Back" functionality bound to "alt + left arrow" and both take me to the previous diagram in the list (not previous diagram in my "click-stack").
But you are right that when I click back button in the broswer via mouse, it behaves correctly.
Perhaps Structurizr JS code binds the arrow key press regardless of modifier keys?

**Comment by simonbrowndotje** [comment]
Thanks, I'm (mostly) on a Mac, so the keyboard shortcuts are different. For some reason, checking the `altKey` property of the event doesn't always work on Windows (it returns `false` more than it should), so I've added a new keyboard shortcut of `b` to go back to the previous diagram.

**Comment by StanleyP** [comment]
This is fantastic! Thank you very very much! And may I ask when could I expect this change to make into official docker images?

**Comment by simonbrowndotje** [comment]
You're welcome. It's already available -> https://hub.docker.com/r/structurizr/lite/tags

**Comment by StanleyP** [comment]
Incredible, you're the boss. Cheers!!

**Comment by StanleyP** [comment]
FYI: Works like a charm! Thanks for this fantastic tool!
