### ISSUE TITLE
Shorten AWS theme tags

### ISSUE THREAD

**Issue by danielmitchell** [structurizr/structurizr#115]
We're creating a number of AWS deployment diagrams with the AWS theme. This works well but it would be even better if the tag names were shorter. Shorter tags means less text to read and write and short service names are consistent with AWS SDKs.

For example the tag `Amazon Web Services - Simple Storage Service` could instead be written `AWS - S3`, which is both shorter and more consistent with other SDKs (e.g. the CDK package is named aws-s3). Same with `Amazon Web Services - Elastic Container Service`/`AWS - ECS`, `Amazon Web Services - Identity and Access Management`/`AWS - IAM` etc.

Structurizr is fantastic and we are getting lots of value from it. Thanks!

**Comment by simonbrowndotje** [comment]
That's not something I can do without breaking the theme for everybody who is already using it, but you can do this yourself very easily:

1. Take a copy of the theme JSON (e.g. https://static.structurizr.com/themes/amazon-web-services-2022.04.30/theme.json)
2. Global search/replace `"tag" : "Amazon Web Services - ` with `"tag" : "AWS - `
3. Publish your theme somewhere accessible via HTTPS (e.g. your own web server or even just a GitHub gist - [example](https://gist.githubusercontent.com/simonbrowndotje/965847ec8820ebd1681fd832b5f78418/raw/69fed95e8cce82be531a073369d31d74db71d4fd/theme.json)).
4. Reference your modified theme via the HTTPS URL; for example:

```
workspace {

    model {
        user = person "User" "A user of my software system."
        softwareSystem = softwareSystem "Software System" "My software system." {
            tags "AWS - Activate"
        }

        user -> softwareSystem "Uses"
    }

    views {
        systemContext softwareSystem "SystemContext" {
            include *
            autoLayout
        }

        theme https://gist.githubusercontent.com/simonbrowndotje/965847ec8820ebd1681fd832b5f78418/raw/69fed95e8cce82be531a073369d31d74db71d4fd/theme.json
    }
    
}
```



Hope that helps.
