### ISSUE TITLE
Structurizr Lite: unable to use dynamic theme from published workspace on the cloud service

### ISSUE THREAD

**Issue by aizzi** [structurizr/structurizr#117]
According to the documentation [here](https://structurizr.com/help/themes) I should be able to use theme defined in a published workspace on cloud. So, I made a workspace, shared it and got the `theme` link as instructed.

Next, I created the following workspace (in the link below, `workspace_id` and `shared_token` are actually the right ones provided to me in the `Sharing Link`) 

```
workspace "Test Themes" "Simple workspace to test functionality of themes" {
    # I want to test if I can use dynamic themes

    model {
        system01 = softwareSystem "Amazon Web Services - Activate" {
            description "Control Element. Should change when using the Amazon theme"
            tags "Amazon Web Services - Activate"
        }

        system02 = softwareSystem "My System" {
            description "Test element. Should change when using my theme. Should be the same as Local System"
            tags "Browser"
        }

        system03 = softwareSystem "Local System" {
            description "The same of My System, but rendered with local style. This is how `My System` should render."
            tags "LocalBrowser"
        }
    }

    views {
        themes "https://static.structurizr.com/themes/amazon-web-services-2022.04.30/theme.json" "https://structurizr.com/share/workspace_id/shared_token/theme"

        systemLandscape "lnd01" {
            title "System Landscape"
            include *
            autolayout "tb"
        }

        styles {
            element "LocalBrowser" {
                shape "WebBrowser"
                background #FFFFFF
                color #000000
                stroke #000000
            }
        }
    }
}
```
When I render this landscape in Structurizr Lite, this is what I get
![image](https://user-images.githubusercontent.com/23487265/187164846-e483a62e-e8fc-43e9-a5df-8c6a7cfcefa5.png)

The element renders correctly when using a local style. It also renders correctly when using one of your published style. But apparently it doesn't load the one published in my workspace. I'm not sure if this is a problem with Structurizr Lite, the cloud, or just me doing something wrong.

Please, note that a `curl https://structurizr.com/share/workspace_id/shared_token/theme` from inside the Structurizr Lite container returns me the proper json. So, apparently it is accessible.

**Comment by simonbrowndotje** [comment]
Themes are loaded from your web browser, so an easy way to see if the theme is being loaded is to open the developer console in your web browser, and look for the request.

**Comment by simonbrowndotje** [comment]
Thanks ... that should be fixed now.
