### ISSUE TITLE
Icons not rendered when using remote themes

### ISSUE THREAD

**Issue by aizzi** [structurizr/structurizr#120]
Hello Simon,

In our org, we have defined a central workspace that holds a common theme to be used across the org. Since yesterday we have noticed that all the icons defined in our centralized repository are not rendered anymore in "client" work-spaces, although they seem correctly included into the theme. Every other aspect of the theme is there, except for the icons.

I spent some time investigating the issue and was finally able to reproduce it.

# Step 1

In "Structurizr Lite" defined the following simple model:

```
workspace "Test" "Icon from remote theme test" {
    # Icons not loaded
    !constant WHITE "#FFFFFF"
    !constant BLACK "#000000"

    model {
        enterprise "test" {
            ss_system = SoftwareSystem "system" {
                description "Apply a specific style"
                tags "External, Bitbucket"
            }
        }
    }

    views {
        themes default

        styles {
            element "External" {
                shape "Hexagon"
                background ${WHITE}
                color ${BLACK}
                stroke ${BLACK}
            }
            element Bitbucket {
                icon "icons/bitbucket.png"
                metadata false
            }
        }

        systemLandscape "dgm01" "Simple Diagram" {
            include *
            autoLayout "lr"
        }
    }
}
```

Rendered locally and verified that the element is indeed visualized as an Hexagon with the Bitbucket icon.

# Step 2

Synched the model in a "Structurizr Cloud" workspace [here](https://structurizr.com/share/76236). Visualized the diagram in the cloud and verified that is indeed rendered as an Hexagon with the Bitbucket icon.

# Step 3

Verified the associated [theme](https://structurizr.com/share/76236/theme) has indeed all the required element's styles

# Step 4

Modified the local model to use the theme in cloud

```
workspace "Test" "Icon from remote theme test" {
    # Icons not loaded
    !constant WHITE "#FFFFFF"
    !constant BLACK "#000000"

    model {
        enterprise "test" {
            ss_system = SoftwareSystem "system" {
                description "Apply a specific style"
                tags "External, Bitbucket"
            }
        }
    }

    views {
        themes default "https://structurizr.com/share/76236/theme"

#        styles {
#            element "External" {
#                shape "Hexagon"
#                background ${WHITE}
#                color ${BLACK}
#                stroke ${BLACK}
#            }
#            element Bitbucket {
#                icon "icons/bitbucket.png"
#                metadata false
#            }
#        }
#
        systemLandscape "dgm01" "Simple Diagram" {
            include *
            autoLayout "lr"
        }
    }
}
```

Rendered the diagram locally and verified that now it is visualized as an hexagon **without the associated icon**.

**Comment by simonbrowndotje** [comment]
Thanks for the detailed information - this should be working again now.

**Comment by aizzi** [comment]
It does. Thank you for the quick fix.
