### ISSUE TITLE
Allow clicking links on relations for diagrams without autolayout in Structurizr Lite

### ISSUE THREAD

**Issue by MGschwindtFW** [structurizr/structurizr#122]
If a relationship has an embedded link, you can usually follow the link by double clicking on the relationship line in the diagram.
However, if autolayout is not set, then instead Structurizr Lite will just create a joint in the relationship line at that point. I could not find an alternative way to follow the link.

I think it should be possible to follow relationship links, when autolayout is not enabled.

##### Example for a relationship with a link

```
component_a -> component_b "Relationship Type" {
    url https://example-url.com
}
```

**Comment by simonbrowndotje** [comment]
With the latest version of Structurizr Lite, you'll be able to do this by double-clicking while holding down the `Alt` key.
