### ISSUE TITLE
Add line thickness / stroke width styling option for Elements

### ISSUE THREAD

**Issue by alexadrien** [structurizr/structurizr#124]
# Context
The stroke-width / line-thickness styling option is already available for relationships but not for Elements ([source](https://structurizr.com/help/notation))
Depending of the size of the diagram, increasing the stroke width of Elements can result in a prettier diagram.

# Request
It would be awesome to have properties to change the stroke width of a diagram. 

# Details
🔽 Screenshots of the documentation
| Elements  | Relationships |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/20789153/195373964-67841362-767f-4132-b18a-3bf81d38a49d.png) |  ![image](https://user-images.githubusercontent.com/20789153/195374832-dac2f4f3-fc1a-4aa1-84c7-be5cd2483836.png)|

**Comment by alexadrien** [comment]
@simonbrowndotje Thank you so much !

**Comment by alexadrien** [comment]
There's something I don't understand on this : 
When I specify a strokeWidth value I get different render results between the exported image and the embedded rendered diagram. 
Here is an illustrating screenshot 
<img width="2124" alt="Capture d’écran 2022-11-14 à 12 29 48" src="https://user-images.githubusercontent.com/20789153/201649661-d2f5508c-22ba-437d-9d79-811aa9596a4d.png">

Would it be possible to make it look the same ?

**Comment by simonbrowndotje** [comment]
I think we've had this discussion before? The way an SVG is rendered when zoomed out is different from how a PNG file is rendered when zoomed out. If you make both diagrams full size (i.e. zoom to actual size/100%), they should look the same.

**Comment by simonbrowndotje** [comment]
I've made some changes to try and make this better, but it might not work on all browsers unfortunately. It seems to work okay on the Chrome family though.
