### ISSUE TITLE
Not able to properly test platform

### ISSUE THREAD

**Issue by SilentGlasses** [structurizr/structurizr#128]
I came across one of your talks and as a result Structurizr. I am enjoying learning about C4 and how to apply it to different use cases outside of just code. Thanks for creating this method.

Am trying to get a local test going but for some reason, we're not at times able to edit diagrams in newly created workspaces when clicking the `Diagram editor` link, it seems like it wants to load the editor but then errors out with a `Please note This workspace is empty.` pop-up and then drops us back into the workspace dashboard (see screenshot).

Also, devs are saying that the UI is not too intuitive, with lots of icons that aren’t clear about what they’ll do until you hover over them.

![Screen Shot 122](https://user-images.githubusercontent.com/22822565/203652792-2ee7e8c5-62f1-46c8-b107-b49222e343d0.png)

**Comment by SilentGlasses** [comment]
Another thing that happens is that when trying to load the `Edit Diagram` from an existing diagram when we are able to create one, it tries to load the full menu of icons but then drops to a very minimal one.

### Tries to load
![Screen Shot 123](https://user-images.githubusercontent.com/22822565/203653220-e8141054-239c-4f29-83fa-9a7f43bee3fb.png)

### But ends up loading
![Screen Shot 124](https://user-images.githubusercontent.com/22822565/203653234-3319d534-2b99-45fc-af47-2f0e2c8c5f71.png)

**Comment by SilentGlasses** [comment]
Seems like, writing a basic **DSL editor** script seems to allow it to load but then just get this `diagram not editable; automatic layout enabled - help` error when trying to edit from there using the **Diagram editor** GUI, but clicking help takes me to an internal help page that doesn't exist.

`http://demo.structurizer.domain.com/help/auto-layout`

**Comment by simonbrowndotje** [comment]
I've fixed the link, which should be https://structurizr.com/help/auto-layout
