### ISSUE TITLE
Generated offline HTML Documentation not displaying diagrams using perspectives

### ISSUE THREAD

**Issue by Beerisforwinners** [structurizr/structurizr#130]
Embedding an image from a certain perspective is working as expected within the documentation in the web application, e.g.:

`![](embed:Containers{perspective=Applicants})`

However, the image is not being embedded within the offline HTML generated using the "Export to offline HTML page" link.

Using latest docker image of structurizr/lite running locally.

**Comment by simonbrowndotje** [comment]
This will be available in build 2915+ ... as suggested, the perspective tooltips will be unavailable in the export.
