### ISSUE TITLE
Include view key in embed postmessage data

### ISSUE THREAD

**Issue by bensmithett** [structurizr/structurizr#131]
Is it possible to include the view key in the postmessage data that is sent upon selecting a diagram when viewing an iframe embed? E.g.

```diff
event: {
  data: {
    aspectRatio: 3.1144278606965172,
    controlsHeight: 55,
    iframe: "myEmbeddedDiagram",
    type: "diagram",
+   diagramKey: "MySystem-Container"  
  }
}
```

I'm using the iframe to embed views from the cloud service in a docs site, and would like to be able to add a bit of JS to update my page's URL when the user selects a different diagram (so they can link to the page with a specific view selected)

**Comment by simonbrowndotje** [comment]
Sure, no problem ... this will be included in the next build (>2888).
