### ISSUE TITLE
Control Font in Relationships

### ISSUE THREAD

**Issue by woutervanranst** [structurizr/structurizr#133]
Is there a way to make the font on the arrows smaller / make the boxes further apart as to allow more space for the text on the arrows so they do not wrap?

Reasoning:
* I want to put the names of the processes that 'use' another component
* There is a Dynamic View for each such process which then shows the detail
* Knowing from the high level diagram what detailed process to look into is valuable

![image](https://user-images.githubusercontent.com/6490925/209957517-2e958ea6-e7e4-4e83-a7d4-1e665b7d32c6.png)

**Comment by simonbrowndotje** [comment]
Yes, you can change the font size of relationships; see https://structurizr.com/help/notation for more.

**Comment by woutervanranst** [comment]
Thank you Simon for the quick response.

For future readers - I m using the .NET SDK, this is the snippet
```
styles.Add(new Structurizr.RelationshipStyle(Structurizr.Tags.Relationship) { FontSize = 18, Width = 400 });
```
