### ISSUE TITLE
Tooltips without an explicit perspective

### ISSUE THREAD

**Issue by iowaz** [structurizr/structurizr#134]
Hi there.

Currently in Structurizr we have the [Perspectives Feature](https://structurizr.com/help/perspectives) which enables Tooltips on specific elements.

Is there any plans to add to add the possibility of using Tooltips without an explicit perspective (maybe linked to a Markdown, plain HTML or simple text)?
Also, is there any way that we can colaborate to this feature?

**Comment by simonbrowndotje** [comment]
Tooltips can be enabled by pressing the 'T' key (or using the toolbar button), and will show additional information such as the name-value properties for the element/relationship.

**Comment by iowaz** [comment]
Ooooh. It doesn't need to have a perspective attached.

Well, I think we can close this issue. Many thanks again @simonbrowndotje . Happy New Year's Eve.

In time: is there any way to donate to the project?
