### ISSUE TITLE
Allow setting to disable specific dialogs

### ISSUE THREAD

**Issue by alshapton** [structurizr/structurizr#136]
Sometimes, when I render a model, I am presented with the following dialog.

<img width="162" alt="image" src="https://user-images.githubusercontent.com/4507152/210752663-433acf66-e6f0-4c34-bf37-a202466ac66c.png">

I would like the ability to switch this off, since my model is not getting any smaller.  It would be great if I could elect not to see this dialog. 

Possible implementations could be a flag e.g. --nodialog on the command line when uploading a model, and/or a UI switch.

This may be an idea that could stretch to a bunch of other dialogs (if there are any).....

**Comment by alshapton** [comment]
> The best solution would be to reduce the number of elements/relationships on the diagram, but you can set a view configuration property to increase the limits though, as follows:
> 
> ```
>     views {
>         properties {
>             "structurizr.maximumElements" "200"
>             "structurizr.maximumRelationships" "200"
>         }
> 
>         ...
> ```

Will this then eliminate the dialog ?

**Comment by simonbrowndotje** [comment]
Yes, if you set the value greater than the number of elements/relationships you have on the diagram.

**Comment by alshapton** [comment]
Yes - this is fine - thanks.
