### ISSUE TITLE
Allow to specify name for containerInstance

### ISSUE THREAD

**Issue by sschutten** [structurizr/structurizr#14]
It would be nice to be able to specify a name for a containerInstance in a deployment diagram. In PaaS cases the containerInstance is it's own deploymentNode. E.g. a Cosmos DB in Microsoft Azure isn't deployed on some node, it becomes it's own instance in the resource group.

In the current setup it requires me to create a deploymentNode with the actual name and create the instance inside it. This clutters the diagram, but more importantly you can't have multiple deployment nodes with the same name, while you can easily have multiple resources in a resource group with the same name. In fact, our naming convention doesn't specify the type in the name of a resource, so we have many resources with the same name.

Instead of this:
```
deploymentNode "myResourceGroup" "Resource Group" "Resource Group" "Microsoft Azure - Resource Groups" {
    deploymentNode "myCosmosDb" "Cosmos DB" "Cosmos DB" "Microsoft Azure - Azure Cosmos DB" {
        databaseInstance = containerInstance database
    }
}
```

I would like to be able to do something like this:
```
deploymentNode myResourceGroup "Resource Group" "Resource Group" "Microsoft Azure - Resource Groups" {
    databaseInstance = containerInstance database "myCosmosDb"
}
```

**Comment by simonbrowndotje** [comment]
I don't know Cosmos DB at all, so please bear with me ... but from what I've read, perhaps you should model the Cosmos DB container as the C4 model container, and that additional deployment node of the Cosmos DB instance then becomes useful? (as I understand it, a single DB can have many containers?)

<img width="381" alt="Screenshot 2021-01-14 at 09 13 43" src="https://user-images.githubusercontent.com/1009874/104569291-d40a2200-5648-11eb-9274-29c181f554f0.png">
