### ISSUE TITLE
Section numbers only on two levels

### ISSUE THREAD

**Issue by plehmann-next** [structurizr/structurizr#145]
Hi! 
In contrast to what is documented in https://structurizr.com/help/documentation/headings, it seems that the section numbering stops on the second usable level (`###` for md) and does not number headings on the third level or below (`####` for md). This may sound like a minor issue but when following the arc42 model in chapter 5 (Building blocks), I find myself using level 4 quite often. Because Structurizr documentation ignores level 1 (`#`), the following example starts on level 2 and so the important descriptions of the black boxes is on level 4.

```
## Building Block View

### Whitebox Overall System

***\<Overview Diagram>***

Motivation:   *\<text explanation>*

Contained Building Blocks:   *\<Description of contained building block (black boxes)>*

Important Interfaces:   *\<Description of important interfaces>*

#### \<Name black box 1>
```

The problem is that level 4 headings are not easily distinguishable from regular paragraph text. In this example, the "Name black box 1" heading has a `font-size` of 22px vs. 20px for regular text (see screen shot). With a section numbering on level 4, the structure of the documentation would be much clearer. Level 4++ should not be included in navigation though, levels 2 and 3 are fine.

![missing section numbers](https://user-images.githubusercontent.com/120407388/217755586-7e4a5acb-4375-4f50-adbd-4049371f248c.png)

Is this a bug or am I using the documentation in a wrong way here? 

Thank you very much!

**Comment by simonbrowndotje** [comment]
The level 4 section headings should appear in build 2937+.

**Comment by plehmann-next** [comment]
Wow, that was lightning fast. I could immediately very the changes in both Structurizr cloud and Lite and it works as expected. Thanks again! 👍
