### ISSUE TITLE
Documentation and ADRs not loading anymore

### ISSUE THREAD

**Issue by aizzi** [structurizr/structurizr#153]
Hello,
I have two workspaces that were working fine up to Feb 22nd. Today, when I open them, I get the following message:

There is a problem loading your workspace - TypeErorr: component.documentation is undefined

I didn't change anything since the last time. The problem happens on both Lite and Cloud.

**Comment by aizzi** [comment]
Here is a reproduction step:

```
workspace "Test Workspace" "A test workspace" {
    # Just create a simple md file in this folder
    !docs documentation

    model {
        ss_TestSoftwareSystem = softwareSystem "Software System" {

            cn_TestContainer = container "Container" {
                # When loading the documentation
                # If you comment this component out, everything works.
                # If not, you get the TypeError: component.documentation is undefined
                cm_TestComponent = component "Component" {
                }
            }
        }        
    }
}
```

**Comment by simonbrowndotje** [comment]
This requires a new Lite build, so I'd revert back to an older build for now until this is done. The cloud service should work, although you may need to do a hard refresh in your web browser.

**Comment by aizzi** [comment]
Both versions work now. Thanks.
