### ISSUE TITLE
ELK layout support

### ISSUE THREAD

**Issue by activey** [structurizr/structurizr#162]
### Description

Recently I'm using Structurizr quite heavily in my private project and stumbled on autLayout issues for more complex scenarios. I've played with D2 Structurizr exported and D2 ELK atuomatic diagram layout which seems to do a really great job.

Would authors consider implementing such layout algorithm for Structurizr? ;)

### Priority

Low

### Resolution

I'm willing to add this feature myself and raise a PR

### More information

I've found a source code of D2 ELK layout implementation here: https://github.com/terrastruct/d2/tree/master/d2layouts/d2elklayout

**Comment by simonbrowndotje** [comment]
> I'm willing to add this feature myself and raise a PR

Thank you ... let me know when you're done with an initial version and I'll take a look. The Structurizr UI uses JointJS to render diagrams, and it looks like there are some ELK integration demos available, which might make a useful starting point for you -> https://github.com/clientIO/joint/tree/master/demo/elk

**Comment by activey** [comment]
Just a question in regards of using JointJS: I've checked the structurizr/ui code and as far I can see there is just D3 and some force simulation applied, can I ask you to point me out where the JointJS is actually used? Many thanks in advance.

**Comment by simonbrowndotje** [comment]
Sure...

- https://github.com/structurizr/ui/blob/main/src/jsp/diagrams.jsp
- https://github.com/structurizr/ui/blob/main/src/js/structurizr-diagram.js
