### ISSUE TITLE
Automatic layout on Component view with no relations

### ISSUE THREAD

**Issue by alleknalle** [structurizr/structurizr#24]
I've created a Component view with some elements without relations. It's just an overview of elements with the same tags. For this view I've enabled automatic layout. But now only a couple of elements are visible. Do you have any idea what I;m doing wrong?

Below the JSON part of the Component view and the output in Structurizr:
```
{
   "title":null,
   "description":"",
   "key":"MessagesView",
   "paperSize":null,
   "automaticLayout":{
      "rankDirection":"TopBottom",
      "rankSeparation":300,
      "nodeSeparation":600,
      "edgeSeparation":200,
      "vertices":false
   },
   "elements":[
      {
         "id":"18",
         "x":null,
         "y":null
      },
      {
         "id":"20",
         "x":null,
         "y":null
      },
      {
         "id":"22",
         "x":null,
         "y":null
      },
      {
         "id":"35",
         "x":null,
         "y":null
      },
      {
         "id":"56",
         "x":null,
         "y":null
      },
      {
         "id":"58",
         "x":null,
         "y":null
      },
      {
         "id":"60",
         "x":null,
         "y":null
      },
      {
         "id":"62",
         "x":null,
         "y":null
      },
      {
         "id":"64",
         "x":null,
         "y":null
      },
      {
         "id":"70",
         "x":null,
         "y":null
      },
      {
         "id":"66",
         "x":null,
         "y":null
      },
      {
         "id":"68",
         "x":null,
         "y":null
      }
   ],
   "relationships":[
      
   ],
   "containerId":"16",
   "externalContainerBoundariesVisible":true
}
```

![image](https://user-images.githubusercontent.com/5603434/113868664-3a1dc580-97b0-11eb-901a-f4460c26bad7.png)

**Comment by simonbrowndotje** [comment]
I would guess that, because there are no relationships, the auto-layout algorithm is treating all elements at the same level, and organising them across the page, which isn't wide enough.

**Comment by alleknalle** [comment]
I just tried it with adding the relations, but it then it also doesn't show in a good way:
![image](https://user-images.githubusercontent.com/5603434/113894081-f5058d80-97c7-11eb-9ed3-6a2ae3f0c68e.png)

All my other views look nice, except this one.

**Comment by simonbrowndotje** [comment]
Without relationships between the majority of elements, the same is happening as before ... the majority of elements are at the same rank/level in the graph, and being positioned side-by-side.  You have a number of options; including:

1. Add relationships between all elements, therefore creating a directed graph, which will work better with the automatic layout algorithm.
2. Modify the node separation of the automatic layout configuration for that view, to make nodes at the same rank/level closer together ([example](http://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/88c1d9f6a2d73c4702faea0fa3264b1f/raw/98ac216f05c66231384347470c3412130a822054/gistfile1.txt))
3. Programmatically set the x,y coordinates for each element in that view before uploading the workspace.
4. Disable automatic layout for that view, and manually organise the elements.

3 or 4 would be my recommended options.

**Comment by alleknalle** [comment]
Okay clear, I will probably go for option 3. Thank you for your advise 👍
