### ISSUE TITLE
Allow cropping diagram images when exporting to PNG

### ISSUE THREAD

**Issue by juanrferia** [structurizr/structurizr#26]
Hello,

I usually export my diagrams as PNG images. Sometimes the images contain big blank areas, which is not convenient when attaching to documentation. So, I manually crop images to remove the blank areas.

I would like to be able to crop diagram images when exporting to PNG. I believe it was already a feature in the past, but somehow it is not posible anymore.

![Screenshot 2021-04-18 at 07 06 59](https://user-images.githubusercontent.com/11686949/115135053-b49ede80-a015-11eb-8d94-808448220623.png)

Thank you!

**Comment by simonbrowndotje** [comment]
That should be back now.

**Comment by juanrferia** [comment]
Yeah, thanks a lot!
