### ISSUE TITLE
Aww Snap browser crash when auto arranging views

### ISSUE THREAD

**Issue by jeffabailey** [structurizr/structurizr#30]
This error occurs when following the steps below.

![image](https://user-images.githubusercontent.com/776901/120388185-a6fc9a00-c2df-11eb-889e-aefe8cafff6d.png)

1. Edit a system context view
2. Add several elements and relationships to the view
3. Choose A6 landscape
4. Press the Auto layout button
5. Choose direction left to right
6. Press Auto layout
7. See the crash error

I'm happy to provide the workspace id over Slack and/or help troubleshoot the issue.

**Comment by jeffabailey** [comment]
I'm not seeing this error occur in Firefox.

**Comment by jeffabailey** [comment]
I used Structurizr in an incognito window Chrome Version 90.0.4430.212, and I was able to reproduce the error.

**Comment by jeffabailey** [comment]
I upgraded to Chrome Version 91.0.4472.77, and it may have fixed the issue.

I'll update here after a week of use. If it's good to go I'll close this issue.

**Comment by jeffabailey** [comment]
I was able to reproduce the issue with Version 91.0.4472.77 today. I followed the same steps listed above to reproduce the issue.

**Comment by simonbrowndotje** [comment]
Closing this since the workspace editor has been discontinued.
