### ISSUE TITLE
Multiple URL association with elements

### ISSUE THREAD

**Issue by jeffabailey** [structurizr/structurizr#31]
Sometimes a system component has documentation in multiple places that are not under an architect's control. Having the ability to enter multiple URLs would help keep references to documentation in one place when creating diagrams.

![image](https://user-images.githubusercontent.com/776901/120846203-a570e300-c526-11eb-8248-2d0081322b51.png)

**Comment by simonbrowndotje** [comment]
Elements can only have a single URL, so I'd probably recommend creating a Markdown/AsciiDoc documentation page with those links and setting that URL as the component's URL.
