### ISSUE TITLE
Source for theme help?

### ISSUE THREAD

**Issue by jean** [structurizr/structurizr#33]
The [theme docs](https://structurizr.com/help/themes) don't actually say how theme styles get applied: the term `tag` does not occur. 
Looking at the [Amazon example](https://structurizr.com/dsl?example=amazon-web-services) and eyeballing the strings on the [theme page](https://structurizr.com/help/theme?url=https://static.structurizr.com/themes/amazon-web-services-2020.04.30/theme.json) one deduces that the element styles should be named in the _tag_ property. 
I'm sure this is obvious to experienced users, but it's a bit baffling for newcomers. 
Is the theme help source available somewhere to submit a PR?

**Comment by jean** [comment]
Ah, the necessary info is under _Tags and styles_ on the [Notation](https://structurizr.com/help/notation) page. A link to that may suffice. (Would be nice if all headings get ids.)

**Comment by simonbrowndotje** [comment]
Thanks, we've added a link to the notation page from [https://structurizr.com/help/themes](https://structurizr.com/help/themes).
