### ISSUE TITLE
Structurizr Lite view resetting to upper-left

### ISSUE THREAD

**Issue by gp-mlezotte** [structurizr/structurizr#36]
Since switching to Structurizr Lite locally (instead of the free on-prem version), I've been experiencing an issue making adjustments to diagrams in the front-end. This appears to be an issue with zoom, as I notice it primarily on larger diagrams. When zoomed in and dragging an element, the view positioning appears to reset periodically. This results in the element that I was moving being pulled into the upper-left section of the diagram. On closer inspection, this appears to happen any time a change is made to the diagram (at least for the couple of changes that I tested).

Here are the repro steps:
1. Open a diagram
2. Zoom into a section of the diagram that is not the upper-left
3. Begin to drag an element
4. After a short amount of time (perhaps a second or so), the view will be reset to the upper-left
5. At the same time, it appears that a "Saving Workspace" message flashes briefly
6. The element being dragged is pulled into the corresponding position in the new view

This is really jarring and frustrating when trying to make small adjustments, as attempting to make a minor tweak can result in the element you're tweaking being pulled into a completely different section of the diagram. Even if you are able to finish dragging before this happens, the view resets so you have to navigate back to your previous position to continue.

My assumption is that this is a result of the auto-save feature in Lite. If so, is it possible to make this feature fully transparent in the UI?

If it helps, I'm using version 92.0.902.62 of Edge.

Please let me know if I can provide any additional info. Thank you!

**Comment by simonbrowndotje** [comment]
Thanks - this should now be fixed.

**Comment by gp-mlezotte** [comment]
This is much better now, thanks for the super quick turn around!
