### ISSUE TITLE
DSL Editor not loading put workspace

### ISSUE THREAD

**Issue by cpoepke** [structurizr/structurizr#37]
I was executing the [GettingStarted](https://github.com/structurizr/java/blob/master/structurizr-examples/src/com/structurizr/example/GettingStarted.java) example on a workspace on Struturizr Cloud. It gets successfully uploaded, the diagrams updated (see screenshot) and exporting the workspace creates a proper json. The workspace editor is working but the DSL editor is not loading the DSL at all. It is still the old version.

<img width="2535" alt="Bildschirmfoto 2021-08-05 um 09 58 42" src="https://user-images.githubusercontent.com/2373209/128315556-67a32fda-7ce1-4267-989d-2703e098a3ff.png">

**Comment by simonbrowndotje** [comment]
That's correct - the Structurizr service doesn't automatically convert workspaces to the DSL format.

**Comment by cpoepke** [comment]
What is the desired behaviour? Are we missing a step to covert?

**Comment by simonbrowndotje** [comment]
You can use the Structurizr CLI to convert a JSON workspace file to the DSL format ([docs](https://github.com/structurizr/cli/blob/master/docs/export.md)), but if you want to use the DSL, I would just recommend using the DSL to create a workspace, rather than the Java client library.

**Comment by cpoepke** [comment]
tbh. when I load a workspace (which includes putting it) that everything in Structurizr Cloud is loading it and displaying the correct data. Which means updating views and dsl in the editor. That already partially happening, even the workspace editor. Hence I would expect the DSL editor to convert and load as well.

Is it a feature that the DSL editor is not converting or inconsistent implementation? Are you considering to add the conversion in the DSL editor?

**Comment by simonbrowndotje** [comment]
As I said, the Structurizr service doesn't automatically convert workspaces to the DSL format(*). The way to think about it is like this ... the web-based DSL editor will only show the DSL that you've provided it:

- If you upload a workspace via the Java client library, you're not providing any DSL, so the DSL editor will be empty.
- If you write a DSL file locally, and use the Structurizr CLI to push that to the cloud service, the DSL editor will reflect the DSL that you have provided.

If you want to use the DSL, I recommend:

1. Writing a local DSL file, and using the Structurizr CLI to push that DSL file to the cloud service.
2. Writing the DSL directly into the online editor.

You should only choose one of these two approaches though. Modifications made in the online DSL editor will not be reflected in your local file. Option 1 is the best approach, as the online DSL editor lacks some features ([docs](https://structurizr.com/help/dsl)). 

(*) the exception to this is the online workspace editor ... this is being discontinued, and the DSL shown there is to help people migrate

**Comment by cpoepke** [comment]
Alright. I will go that approach.

I highly recommend to add the automatic conversion of workspaces to DSL in the service. From an UX perspective this is very much needed.

**Comment by simonbrowndotje** [comment]
> I highly recommend to add the automatic conversion of workspaces to DSL in the service. From an UX perspective this is very much needed.

If you're using the Java client library (and writing Java code) to create a workspace, what's the value in the cloud service generating DSL for you? (any changes you make to the DSL won't be reflected in your Java code)

**Comment by cpoepke** [comment]
> > I highly recommend to add the automatic conversion of workspaces to DSL in the service. From an UX perspective this is very much needed.
> 
> If you're using the Java client library (and writing Java code) to create a workspace, what's the value in the cloud service generating DSL for you? (any changes you make to the DSL won't be reflected in your Java code)

Actually we want to generate the basic workspace structure in Java by pulling data from DataDog and then amending it in the DSL editor later on with additional information.

**Comment by simonbrowndotje** [comment]
If you want to convert a workspace created using the Java client library to the DSL, before pushing to the cloud service, you can add [a dependency to the DSL library](https://search.maven.org/artifact/com.structurizr/structurizr-dsl) and do the following:

```
Workspace workspace = new Workspace("Name", "Description");
// add information from Datadog

StructurizrDslFormatter formatter = new StructurizrDslFormatter();
String dsl = formatter.format(WorkspaceUtils.toJson(workspace, false));
                
// save DSL to disk
```

This will give you the DSL to upload using the CLI. This will work as a one-off task, but you will lose any DSL changes if you repeat this process.

**Comment by cpoepke** [comment]
Thanks for the tip. Actually we want to have a pipeline updating the workspace continuously. Since the workspace would be our source of the architecture documentation where we would pull diagrams from confluence.
