### ISSUE TITLE
Please note that the workspace editor is being discontinued

### ISSUE THREAD

**Issue by jeffabailey** [structurizr/structurizr#38]
I just noticed this banner in the structurizr.com UI.

_Please note that the workspace editor is being discontinued. It will be available for free accounts until 30th September 2021 and for paid subscriptions until 28th February 2022. We recommend converting your workspace to the Structurizr DSL format. Please contact us if you need assistance._

That's unfortunate, as that's the main reason I signed up and started using Structurizr. I can easily reuse elements in various diagrams, making it less of a burden when creating tailored diagrams for specific audiences.

Is the recommendation to build diagrams using the DSL generated from the >_DSL tab to meet the same use case?

I see that there is an !include directive with the DSL, maybe that will help?

**Comment by simonbrowndotje** [comment]
> Is the recommendation to build diagrams using the DSL generated from the >_DSL tab to meet the same use case?

Yes, the DSL is the recommended way to create workspaces, and supports the same modelling concept as the workspace editor. The DSL displayed in the `DSL` tab is a conversion of your current workspace to the DSL format. You can take this DSL and use it in the online DSL editor, or via the Structurizr CLI. The CLI is the recommended approach, as it provides more functionality than the online DSL editor (see [Structurizr - Help - DSL](https://structurizr.com/help/dsl) for more details).

**Comment by simonbrowndotje** [comment]
> I see that there is an !include directive with the DSL, maybe that will help?

The `!include` directive provides a way to reuse DSL fragments across workspaces. For example, imagine you have 3 workspaces, each documenting a single software system, yet they all use a common set of software systems within the environment. You can define those shared software systems in a DSL fragment, and use the `!include` directive to include them into all 3 workspaces. This is one example of why the DSL is much more powerful than the workspace editor. Please note that the `!include` directive is designed to work with the CLI.

**Comment by jeffabailey** [comment]
Thanks!

**Comment by simonbrowndotje** [comment]
You're welcome! There are two other benefits of using the DSL:

1. It's independent of any diagramming tool (you can render using Structurizr, PlantUML, etc ... see [https://structurizr.org/#rendering](https://structurizr.org/#rendering) for more details).
2. If you only need diagrams, and don't need to share your workspace, you can use the free Structurizr Lite product (see [Getting started with Structurizr Lite](https://dev.to/simonbrown/getting-started-with-structurizr-lite-27d0)).
