### ISSUE TITLE
Documentation admonition icons don't render

### ISSUE THREAD

**Issue by Riduidel** [structurizr/structurizr#41]
When using an asciidoc [admonition block](https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/), the used icon is not rendered. Instead, the admonition text is displayed.

Here is an example source document

```
== Software architecture

IMPORTANT: This architecture document focuses on interconnections between systems, and not on systems inner workings
```

And the resulting incorrect html screenshot

![image](https://user-images.githubusercontent.com/171018/135891536-5c25d1df-5f1e-4234-8cdb-9e66fc028625.png)

**Comment by simonbrowndotje** [comment]
Structurizr's documentation renderer doesn't support the full feature set provided by Markdown/AsciiDoc, but the admonition blocks will now render with some colour.

<img width="1104" alt="Screenshot 2021-10-05 at 07 56 26" src="https://user-images.githubusercontent.com/1009874/135974930-d7b12225-6553-4820-88ea-0cd4fcae0114.png">
