### ISSUE TITLE
Augment documentation rendering abilities with asciidoctor-kroki

### ISSUE THREAD

**Issue by Riduidel** [structurizr/structurizr#42]
I've tried to use asciidoctor-diagram to render PlantUML sequence diagrams previously, but it was ... not so convenient.
Would it be possible to add to structurizr (and structurizr-lite) the ability to render diagrams using [asciidoctor-kroki](https://github.com/Mogztter/asciidoctor-kroki). Indeed, kroki supports more diagram types than asciidoctor-diagram, and it is easier to use an alternative server (which would be very nice to add using configuration).

**Comment by simonbrowndotje** [comment]
I have no plans to support this out of the box, but you could write something like a DSL plugin to pre-process Kroki diagram definitions that you include in your Markdown/AsciiDoc. Here's an example to get you started -> https://github.com/structurizr/dsl-plugins/tree/main/src/main/java/com/structurizr/dsl/plugins/plantuml
