### ISSUE TITLE
Structurizr Lite does not find diagrams

### ISSUE THREAD

**Issue by ComeChao** [structurizr/structurizr#47]
I followed the getting started with structurizr lite guidance (**https://dev.to/simonbrown/getting-started-with-structurizr-lite-27d0**) and ran into this error: **ERROR com.structurizr.lite.web.ApiController - com.structurizr.lite.web.ApiException**

I have Docker Desktop 4.2.0 (70708) running on Windows using Linux containers.

I created this folder: c:\structurizr.

I tried several variations of: **docker run -it --rm -p 8080:8080 -v /structurizr:/usr/local/structurizr structurizr/lite**

No matter what I do I always get an error when I navigate to: **http://localhost:8080/workspace/diagrams**
![structurizr1](https://user-images.githubusercontent.com/7957369/141696281-960a34e8-efdb-4e16-8d0b-5b579dbbfb6d.JPG)

The log stream has these 4 last entries:
14-Nov-2021 19:50:49.109 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [5,810] ms
14-Nov-2021 19:50:49.123 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
14-Nov-2021 19:50:49.137 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [5914] milliseconds
2021-11-14 19:51:08,329 [http-nio-8080-exec-4] ERROR com.structurizr.lite.web.ApiController  - com.structurizr.lite.web.ApiException

I am sure I missed something. 

Please help!

**Comment by simonbrowndotje** [comment]
Do you see any error messages in the web browser's developer console?

**Comment by simonbrowndotje** [comment]
I've just installed Docker on a fresh Windows VM, and did the following, which worked as expected:

```
docker pull structurizr/lite
docker run -it --rm -p 8080:8080 -v c:\Users\simon\lite:/usr/local/structurizr structurizr/lite
```

Upon starting the container, I was asked:

1. Would I like to share `c:\users\simon\lite` with Docker.
2. Would I allow network connections to the Docker process.

I suspect either your mount path is incorrect, or access to the folder/network port is being blocked.

**Comment by ComeChao** [comment]
Event though I was never asked questions 1 and 2 above, I think you are probably right: the mount path is incorrect was incorrect. I can see the diagram now!
![image](https://user-images.githubusercontent.com/7957369/142876365-d007a0de-fb6c-4b01-b72e-a9c62a7c77cd.png)


Thank you so  much for your help!
