### ISSUE TITLE
Usability feedback from a pair of fresh eyes

### ISSUE THREAD

**Issue by jerkstorecaller** [structurizr/structurizr#48]
This is gonna be a messy wall of text, sorry. I initially just wanted to open an issue to improve the doc.

I'll just state my context, so you know what kind of user I am: I work alone with about 8 interconnected systems. I will soon have a co-worker, and I'm trying to write doc to help them understand/visualize the global solution better. When I found out about Structurizr, I was really glad, I imagined having an interactive view where you can zoom in on components, and then on subcomponents. Your Google Maps analogy was what sold me. Plus, it seemed simple to use at a glance.

I used Structurizr Lite for the 1st time a month or so back to write some doc, and overall liked it. The annoying parts:

1. Having to define the views for my models, it just felt like pointless boilerplate. I wanted to show everything, and here I am copy-pasting views with "include *, autoLayout" and just changing the element ID. I had to learn about structurizr more than I felt I should in order to create them without errors (I had to specify container, component, etc). Still, I was creating nice diagrams by copy-pasting a couple of lines, so it's all good.
2. Another annoying part, was how the web interface lacked the Google Maps-like interactiveness I imagined. I'd be pointing with my mouse cursor at something, thinking "now let's zoom to that", then having to type the name to find it in Quick Navigation.
3. Having views display badly by default, which made me create https://github.com/structurizr/structurizr/issues/44 
4. Diagrams were hideous compared to the website's examples until I found out about "theme default". (this isn't as obvious as it seems, for example https://structurizr.com/dsl doesn't include "theme default", and yet the generated result has that rich theme)
5. A lot of the time when I feel I just need to scratch the surface of something, I'll just go from an example and try to wing it without learning, until I need to dig deeper. I feel with Structurizr usage examples are scattered about and not obvious to follow, and the examples in the cli repo jump you all over the place instead of being a single non-trivial example defined in in workspace.dsl with no includes. language-reference.md was just a terse technical reference, not appropriate for "winging it". So I feel like I had to dig in and learn more than I felt I should.

Overall the benefits of Structurizr outweighed the cons, so I just sucked it up. Similar to my feelings about git (which has degree of magnitude more complexity/hygiene issues)

**1: pointless views almost mitigated**
I didn't use it for a month, and came back to it today. I expanded a container's definition to include its components, and was puzzled the diagram wasn't updating in my browser. I had forgotten that I had to add a new component view definition at the bottom. I thought "this is so annoying, having to constantly define these boilerplate autolayout views, I just want to show everything, why do I have to spell it out". Out of curiosity, I deleted the entire views {} object, hoping against hope there might be some nice automatic behavior defined. And sure enough, Structurizr Lite generated all my diagrams, without my boilerplate. Whoa, amazing!

I went back to the doc, and I guess yeah, language-reference.md kinda sorta mentions it. After a bunch of syntax rules, the last entry is a something structurizr-cli having defaults, and if you click the links it takes you to a different repo that tells you cli will auto-generate views if you don't have any. I'm a Lite user, what reason did I have to believe this applied to me? I never even click the link until today, and I think other users will be in the same boat.

I think this is a feature that you should make way more obvious in the doc, eg at structurizr.com, https://github.com/structurizr/dsl/blob/master/docs/language-reference.md and https://github.com/structurizr/java/blob/master/docs/views.md .

As great as this feature is, there are a few shortcomings that make it unsuitable to use, none of it its fault:

1. From what I can see, it's not possible for me to have autogenerated views AND have the nice icons and colors from "theme default".  So I have to pick between simplicity + ugliness or complexity + beauty. I don't think I should have to. I think I should be able to set globalOptions : { views.theme: default } somewhere and have simplicity + beauty.
2. Consider a view with autoLayout and lots of elements such as the one I show here: https://github.com/structurizr/structurizr/issues/44#issuecomment-946000287 . As you can see, there's overlaps that make it unreadable. So people will not use autoLayout, which generates an even worse unreadable mess, then when browsing, will click the autoLayout button to turn the mess into neatness, and follow that up with manual adjustments to relationships to get the desired result, as you explain at https://github.com/structurizr/structurizr/issues/44#issuecomment-946418392 .  By using auto-generated view, autoLayout is enabled, so adjustments on bad views become impossible, because your options are either all autogenerated views with forced autoLayout, or none. Would it be possible to allow people to somehow define "I want fully autogenerated views, but for the autogenerated systemX-containerY-view, I want to disable autoLayout"

**2: interactivity greatly improved**
Also today, I found out another thing by accident, that you can double-click elements with + sign to jump to that element's zoomed-in diagram, greatly improving the interactivity of the webpage. That was super cool and convenient. I think you might think it's too obvious to bother documenting, idk, but I'm sure I'm not the only dum dum among your users. Why not mention that on the help page or Quick Navigation page? Or show it in the popup on first launch.

**As for the rest...**

This is getting long so I'll try to cut to the point.

* The default should be showing all possible views. Think about it, in what scenario would I want to NOT generate all the possible diagrams for the models I made the effort of writing? And is that scenario more likely than the one where I want to see all the diagrams? You provide good interactivity for jumping between nodes, I can simply ignore those I don't want, e.g. not double-click them, so generating everything should be the default.
* "theme default" should be the global Structurizr default theme, the diagrams generated are so much prettier than without it. Whatever ugly theme (or absence of theme) you use when we don't specify it, THAT should be the one requiring the user to manually select it. Perhaps there could ne an override.json config file to let users apply theme/layout customizations without modifying the DSL if you're worried about backwards compat.
* Why wouldn't autoLayout be the default? I mean, think about it: autoLayout=Off means 100% chance of an unreadable diagram the user MUST tweak, even for the simplest view. autoLayout=On is a 90% chance of a great diagram, based on my anecdotal data. So why is the one that requires user tweaks the default? Even if autoLayout=Off, why not apply the same processing as autoLayout=On and render that pretty diagram first, then let them continue to tweak manually? If you do that, then we don't even NEED the option of autoLayout, we have the best of both worlds. 
* A worse alternative to the above if you can't do it for technical reasons: when browsing the webpage, allow people to override autoLayout at will, even if it's enabled in the DSL. If they can get better diagrams by tweaking an autoLayout diagram, why shouldn't they be able to? 

**Conclusion**

I think this tool would gain more users by focusing its defaults towards convenience. I think that better represents the needs of a majority of the users, too, it's the 20/80 rule. It's fine to be flexible to support power users, but the defaults shouldn't be catered to them. Not if you want to maximize adoption. It's Current Year, people want to move mountains with little effort. I mean, look at NodeRed's popularity vs Apache Airflow/Beam. A system easy enough to be used by kids on a Raspberry Pi ends up seeing more use even in industrial factories. Look at Markdown, Hugo. People just want to press X to win, man.

Anyway, thanks for making this nice tool. I hope my feedback can help you improve it. I'm not asking for any changes, my goal here is for you to get feedback from a fresh user and weigh it against things you heard from others, and this helps you make decisions. Cheers.

**Comment by simonbrowndotje** [comment]
Thanks for the feedback. Rather than struggling along, feel free to join the Slack group and ask any questions if you get stuck. To answer your questions here...

> From what I can see, it's not possible for me to have autogenerated views AND have the nice icons and colors from "theme default".

This will do both ... default views, plus the default theme:

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }
    
    views {
        theme default
    }

}
```

> Would it be possible to allow people to somehow define "I want fully autogenerated views, but for the autogenerated systemX-containerY-view, I want to disable autoLayout"

You can do this with the scripting support, for example:

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }
    
    views {
        theme default
    }

    !script groovy {
        workspace.views.createDefaultViews()
        workspace.views.views.find { it.key == 'SoftwareSystem-SystemContext' }.disableAutomaticLayout()
    }

}
```

> Also today, I found out another thing by accident, that you can double-click elements with + sign to jump to that element's zoomed-in diagram, greatly improving the interactivity of the webpage.

As a general rule, the Structurizr renderer (Lite, cloud service, on-premises installation) is documented at https://structurizr.com/help ... and diagram navigation is documented in a couple of places:

 - https://structurizr.com/help/about
 - https://structurizr.com/help/diagram-navigation

This is a work in progress, but there's a "cookbook" that explains how some of the DSL features work -> https://github.com/structurizr/dsl/tree/master/docs/cookbook#readme ... you might find this a better starting point than the language reference, etc. I hope that helps.

**Comment by jerkstorecaller** [comment]
Sorry, I could've sworn I tried "views { theme default }" and it complained about no views defined. But trying again, yeah it works. 

The cookbook seems nice, and I've installed Slack and joined. :)
