### ISSUE TITLE
Is it possible to push dsl with the web-API?

### ISSUE THREAD

**Issue by Mafti** [structurizr/structurizr#51]
Hi,

It seems to me the dsl of C4 is easier to use. Is there a way to upload the dsl to structurizr instead of json?
Currently I see the webAPI only supports json.

I know it can be done with the CLI, but I prefer a webservice :)

**Comment by simonbrowndotje** [comment]
The CLI uses the same web API, so that would be my recommendation for pushing a DSL workspace to the cloud service/on-premises installation.
