### ISSUE TITLE
DSL to JSON exporter unnecessarily escapes single quote

### ISSUE THREAD

**Issue by souliane** [structurizr/structurizr#52]
Hi,

to export the DSL to JSON on https://structurizr.com/dsl?example=big-bank-plc produces on line 245:
`          "description" : "Delivers to the customer\'s web browser",`

This won't be parsed by all JSON parser (it fails for instance with python 3.10 built-in json library, and also with https://jsonlint.com/).

**Comment by simonbrowndotje** [comment]
Transferring this issue since it only affects the DSL demo page.

**Comment by simonbrowndotje** [comment]
I've removed the JSON export from the demo page ... this wasn't really needed on there anyway.
