### ISSUE TITLE
Structurizr/CLI push did not update locally changed shape of relationship line

### ISSUE THREAD

**Issue by vlcinsky** [structurizr/structurizr#58]
Problem: Locally (via structurizr/lite) made changes are not visible after structurizl/cli push on the server

workspace: 72251

Steps:
- using structurizr/lite:
  - create the workspace
- using structurizr/cloud (trial):
  - creat new workspace and upload the workspace.json
  - fix layout (positions of elements, shapes of relationships)
  - unlock the environment
- using structurizr/cli:
  - structurizr.sh pull
  - rename the workspace-72251.json to workspace.json
- using structurizr/lite
  - run it (to edit workspace.json)
  - do updates to workspace.dsl
  - update layouts again
- using structurizr/cli:
  - structurizr.sh push the workspace.json
- using structurizr/cloud
  - show the updated model
  - find some detail you want to update - such as shape of relationship line 
- using structurizr/lite
  - run it (with the workspace.json used in last cli push)
  - edit (locally) some relationship line shapes
- using structurizr/cli:
  - structurizr.sh push the workspace.json
- using structurizr/cloud:
  - try to show the lates version to check, if the relationship line shape has changed

The problem is, I do not see the relationship line shape change in the structurizr/cloud.

Even trying to do a few more local changes (without structrurizr/cli pull) followed by structurizr/cli push did not change the lines.

The problem might be caused by my misunderstanding.

I am confused in following things:
- shall structurizer/cli use .dsl or .json workspace file?
- is locally updated layout (shape of relationship) pushed via cli?
- is push completelly replacing the workspace or things are merged?

**Comment by simonbrowndotje** [comment]
The CLI should merge your workspace layout information unless the `-merge` parameter is set to `false`. That said, you may just want to use the auto-sync feature of Structurizr Lite (https://structurizr.com/help/lite/sync) rather than manually pulling and pushing the workspace.

**Comment by vlcinsky** [comment]
@simonbrowndotje thanks for the auto-sync hint - it works great.
