### ISSUE TITLE
Support default credential provider chain for S3 credentials

### ISSUE THREAD

**Issue by barrycommins** [structurizr/structurizr#59]
Hi,

we'd like to use the HA add-on with S3, but can't use access tokens and secrets.

Would it be possible to support the default provider chain?

The Java SDK has support for delegating to the default provider chain if you don't explicitly provide credentials
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default

The change should be something like:

```java
if (awsS3AccessKeyId != null || awsS3SecretAccessKey != null) {
    // do what you do now, for backward compatibility
} else {
    AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                       .withRegion(region)
                       .build();
}
```

Thank you!

**Comment by simonbrowndotje** [comment]
This is now available in build 2647.

**Comment by barrycommins** [comment]
That's excellent, thanks for the super quick work Simon
