### ISSUE TITLE
Proposal: Structurizr Cloud Settings providing content of structurizr.properties

### ISSUE THREAD

**Issue by vlcinsky** [structurizr/structurizr#60]
The Settings page on Structurizr Cloud on url https://structurizr.com/workspace/{workspaceid}/settings provides nicelly formatted values for calling structurizr CLI.

The proposal is to add there a section, where would be rendered relevant content of `structurizr.properties` as used for auto-sync configuration for structurizr CLI.

**Comment by simonbrowndotje** [comment]
Thanks - that's all done.

**Comment by vlcinsky** [comment]
Great Simon. The reaction time to issues is really astonishing.

Hint: On the new page, consider linking the "auto-sync" text to help. Like:

> Structurizr Lite [auto-sync](https://structurizr.com/help/lite/sync) configuration
