### ISSUE TITLE
Add aws-java-sdk-sts jar to on-prem WAR file

### ISSUE THREAD

**Issue by barrycommins** [structurizr/structurizr#61]
Hi Simon,

I have one more request related to #59 , if you don't mind?

After a bit of digging, I discovered that the default provider chain can delegate to STS. but you need to have aws-sdk-java-sts on the classpath.

It's loaded via reflection in this class: https://github.com/aws/aws-sdk-java/blob/1.12.162/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/securitytoken/STSProfileCredentialsServiceProvider.java#L24

It's also mentioned in this issue: https://github.com/aws/aws-sdk-java/issues/2283

Once that's in place, everything works as described here: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

Would it be possible to add that library to the WAR please?

**Comment by simonbrowndotje** [comment]
Sure, that's all done.
