### ISSUE TITLE
Graph, showing ADR interconnections, is showing only some links

### ISSUE THREAD

**Issue by vlcinsky** [structurizr/structurizr#62]
A am using bash based adr-tools and from there command:
```
$ adr link 7 "is required by" 6 "requires"
$ adr link 7 "is required by" 5 "requires"
$ adr link 7 "is required by" 4 "requires"
```
The pages are showing those links in texts (so ADR # 7 is showing three liks to 4, 5 and 6, but the graph is showing only the links, which appear as the first one in all participating decision.

It would be nice to show all relationships.

**Comment by simonbrowndotje** [comment]
There's a piece of work in progress at the moment that is:

- enhancing the way ADRs are stored in the JSON workspace
- splitting the adr-tools importer away from the java-extensions project, and defining an interface to make it pluggable (via the DSL, for example), for parsing ADRs created by different tools in different formats
- moving the ADRs link parsing logic from the Structurizr UI to the above, to better support showing links between ADRs

This should all be available next month.

**Comment by vlcinsky** [comment]
This sounds really great.

I was just wondering, if e.g enumeration literals like "Proposed", "Accepted", "Superseded", "Deprecated" and "Rejected" could be translatable similarly as done by DSL today in [terminology](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#terminology)

But as I see there is a piece of work in progress I will step away to let the energy flow in the direction which looks very promising to me.

**Comment by simonbrowndotje** [comment]
Thanks. Yes, the enum has gone, which provides an easier way for teams to build their own custom ADR importers. 👍

**Comment by simonbrowndotje** [comment]
If you're using the DSL to author your workspace, the latest version of Structurizr Lite now has the new version of the documentation/ADRs support.

**Comment by vlcinsky** [comment]
Great, I see, the visualization now reflects all links, even if there are multiple for one node (what often was not the case before).
It looks good.

When moving the nodes (in the preview), it shows logical clustering of related decisions.

I was going to propose an option of tagging (or assigning perspectives) decisions (like "architecture", "security", "deployment" etc.), current "clustering" by links is partially fulfilling my needs.

![obrazek](https://user-images.githubusercontent.com/635911/156133492-72fb7764-b60d-4cb1-abb9-0e0cea5d823e.png)

**Comment by vlcinsky** [comment]
@simonbrowndotje I have no idea how you do the nice live graph of links but it looks to me like planets.

An idea: consider giving each node/planet gravity related on number of links + 1. It could possibly cause more important decisions to create visible cluster.

Just an idea, I am happy with the status as it is.

**Comment by simonbrowndotje** [comment]
Thanks! It's a d3.js force-directed graph -> https://observablehq.com/@d3/force-directed-graph
