### ISSUE TITLE
Latest version of Structurizr/Lite fails to load ADRs

### ISSUE THREAD

**Issue by aizzi** [structurizr/structurizr#64]
Since yesterday, I'm having problems in loading the ADRs in Structurizr/Lite. Whenever I enable the line

```
!adrs decisions
```
in the workspace, I get the following error in loading the workspace in the UI:

Workspace 1 could not be loaded using the API at http://localhost:8080/api

```
Status: 400 - error
Message: workspace.dsl: Error importing ADRs from /usr/local/structurizr/decisions: java.lang.NullPointerException: Cannot invoke "com.structurizr.documentation.Decision.getId()" because "decision" is null at line 40: !adrs decisions

The JavaScript/developer console in your web browser may have more information about this error. Please try again or contact help@structurizr.com for assistance.
```
Everything was working fine until yesterday (at least, this is when I started noticing the problem). The Cloud version is apparently fine.

**Comment by simonbrowndotje** [comment]
Give the latest build (2680) a try - I suspect you have a broken link somewhere in your ADRs. If that doesn't work, please attach a reproducible example or send your ADRs to help@structurizr.com so that we can take a closer look.

**Comment by aizzi** [comment]
The latest build has fixed the problem. Thanks.

BTW: how can I check which version I'm running?

**Comment by simonbrowndotje** [comment]
Great, thanks! The build number is in the logs, which are displayed in the console when starting the Docker container.
