### ISSUE TITLE
Components do not open "url" link

### ISSUE THREAD

**Issue by aizzi** [structurizr/structurizr#65]
I have created the following component:

```
cm_core_io_vasMessage = component "VAS Message Payload" {
    description "VAS Payload to be forwarded in the processing chain"
    technology "NATS"
    tags "Package"
    url "working link to the asyncapi documenation page for the message"
}
```
However, although I can correctly see the url associated to the icon in the diagram, when I double click on it nothing happens. Verified on last Lite and on Cloud (free version for now).

**Comment by simonbrowndotje** [comment]
Apologies, this should be working again now.

**Comment by aizzi** [comment]
I confirm the fix. Thanks.
