### ISSUE TITLE
Structurizr Lite readability issues with explorations and decision graphs

### ISSUE THREAD

**Issue by gp-mlezotte** [structurizr/structurizr#66]
I've been using Structurizr Lite since it was first introduced, and have always had readability issues with both explorations and decision graphs (to the point of them being almost unusable). I realized today that this was due to using the dark theme in my browser (Edge / Chrome). I'm hoping that some adjustments can be made to make these graphs readable in the dark theme as well as the light theme. For now, I can manually switch my browser to the light theme as needed, it's just a bit of a hassle. Thanks!

**Comment by simonbrowndotje** [comment]
It turns out there was a CSS style missing - the graph backgrounds should be dark now, rather than white.

**Comment by gp-mlezotte** [comment]
It looks great now, thank you so much!
