### ISSUE TITLE
Latest structurizr/lite docker image fails to import dsl file

### ISSUE THREAD

**Issue by nikasf** [structurizr/structurizr#69]
I was working fine with the installation of structurizr/lite docker image of 2021-12-22, but last week I got a new laptop and installed the latest version but my workspace.dsl(~1000 lines) can not be imported because of spaces before and after the symbol '->' . 
At least I think this is the problem because when I removed them from the first line of the error, it went to the next line with the same issue and so on. 
It would be nice if this issue could be fixed and continue working as before.

**Comment by simonbrowndotje** [comment]
I think you'll need to surround your relationship expressions in double-quotes; see https://github.com/structurizr/dsl/blob/master/docs/changelog.md#1180-20th-february-2022 for more.

**Comment by nikasf** [comment]
Thank you very much for your immediate reply.
