### ISSUE TITLE
Newlines in perspective descriptions

### ISSUE THREAD

**Issue by gp-mlezotte** [structurizr/structurizr#70]
I frequently put multiple pieces of information in my perspectives, and would really like to be able put each item on a different line to help with readability. Unfortunately, every attempt I've made so far at introducing a newline has failed and is just directly displayed on the diagram. Is there any way to introduce a newline in these descriptions?

**Comment by simonbrowndotje** [comment]
This works for me:

```
workspace {

    model {
        softwareSystem = softwareSystem "Software System"  {
            perspectives {
                "Security" "Line 1\nLine 2"
            }
        }
    }

}
```

**Comment by gp-mlezotte** [comment]
I thought that I had tried that, but must have neglected to refresh or something! Thank you, and sorry to bug you with this!
