### ISSUE TITLE
Intellicode for the Structurizr DSL?

### ISSUE THREAD

**Issue by jeffabailey** [structurizr/structurizr#74]
Is there a language server & intellicode solution somewhere for Structurizr?

I don't see any for VSCode, but there is one in the works.

https://marketplace.visualstudio.com/items?itemName=systemticks.c4-dsl-extension

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/776901/164550243-3063aa1f-ff05-40d2-96ac-7edf974421a7.png">

**Comment by simonbrowndotje** [comment]
Nothing that I'm aware of.
