### ISSUE TITLE
Request: Support for HTML in Markdown

### ISSUE THREAD

**Issue by phxnsharp** [structurizr/structurizr#77]
Currently any HTML tags in the markdown of the documentation or ADR items is escaped and printed literally in the output. 

Reason we want this is that we like to create decision matrices when working on ADRs. We have previously been doing these in word where columns represent options being considered and rows indicate critical requirements to be met. It is convenient to have:
 - newline breaks in cells
 - tooltips or comments for additional information in a cell
 - color coding for "meets", "does not meet", and "partially meets" the requirement. 

Without at least some HTML tags available, markdown does not support any of those three features.

**Comment by simonbrowndotje** [comment]
This is now available by default in Lite, and optionally in the on-premises installation (via a property named `structurizr.safeMode` that needs to be set to false -> https://structurizr.com/share/18571/documentation#https). It's not available in the cloud service though.
