### ISSUE TITLE
Provide a way to disable the online DSL editor

### ISSUE THREAD

**Issue by simonbrowndotje** [structurizr/structurizr#79]
It would be nice to add a way to disable the online DSL editor, thereby forcing users to push their workspace via Structurizr Lite and/or the CLI.

**Comment by pirivan** [comment]
This is the `properties` block referenced in the above [link](https://structurizr.com/help/dsl):
```
properties {
        "structurizr.dslEditor" "false"
}
```

Adding this block at the top level of my `workspace.dsl` file, as suggested in the docs, gives me the following error:
```
com.structurizr.dsl.StructurizrDslParserException: Unexpected tokens at line 2: properties {
```

I tried adding it to the `views` section instead and then there are no errors. However, this doesn't disable the editor on the UI.

Where then should the `properties` block go?
