### ISSUE TITLE
Diagram pinned to top of viewport when zooming out

### ISSUE THREAD

**Issue by simonbrowndotje** [structurizr/structurizr#80]
When zooming out, the diagram gets pinned to the top of the viewport (screenshot attached). It would be nice to centre the diagram in the viewport instead.

![Screenshot 2022-05-17 at 17 52 13](https://user-images.githubusercontent.com/1009874/168867615-ecc48b25-213a-41ae-8718-01022d7bd812.png)

**Comment by fabiocarneiro** [comment]
I was the one reporting this on the Zendesk Support. I think this would definetely be an improvement,but might not be enough.

I think the zoom should always be related to where the cursor is. For example, if I have zoom 10% and I hover over a the letter C of the "Configuration User" in the image provided by @simonbrowndotje, then I scroll to zoom 300%, I should still be hovering that exact same letter C.

The current behavior seems to always zoom based on the center of the diagram.

**Comment by simonbrowndotje** [comment]
OK, so there are two issues here ... apologies, but your Zendesk ticket isn't very clear.

1. The diagram is pinned to the top of the page. That's resolved, but not released, and represented by this issue.
2. When scrolling with the mouse wheel (or ctrl+trackpad), the diagram should zoom in/out using the mouse pointer as the reference/centre point. I will open a new issue for this -> #81.
