### ISSUE TITLE
Zooming diagrams with mouse-wheel (or ctrl+trackpad) should use the mouse pointer as the reference point

### ISSUE THREAD

**Issue by simonbrowndotje** [structurizr/structurizr#81]
Split from #80:

> I think the zoom should always be related to where the cursor is. For example, if I have zoom 10% and I hover over a the letter C of the "Configuration User" in the image provided by @simonbrowndotje, then I scroll to zoom 300%, I should still be hovering that exact same letter C.

> The current behavior seems to always zoom based on the center of the diagram.

> The suggested approach basically allow you to navigate by zooming out, moving the cursor, and zooming in again on another location, without having to click+hold and drag (similar to Figma)

**Comment by simonbrowndotje** [comment]
The zooming behaviour has now been improved.

**Comment by fabiocarneiro** [comment]
Wow!! Tested and just perfect! :heart:
