### ISSUE TITLE
Have consistent Zoom and Drag behavior across all diagram viewers and editors

### ISSUE THREAD

**Issue by fabiocarneiro** [structurizr/structurizr#83]
On the Diagram Viewer it is possible to drag the diagram, but the same is not possible on the editor
On the Graph Explorer is not possible either to zoom (Ctrl+wheel) or drag
On Dependencies Explorer, it is not possible to zoom with +/- or ctrl+wheel, but you must use the ugly buttons on the top.

**Comment by simonbrowndotje** [comment]
Closing this issue ... the explorers now have no zoom buttons, but work better when the browser window is resized.
