### ISSUE TITLE
Provide a way to order the documentation's sections

### ISSUE THREAD

**Issue by aizzi** [structurizr/structurizr#84]
I'm documenting a platform (`VAS Platform`) with four software systems:

- `VAS Core Components`
- `VAS Applications`
- `VAS Infrastructure`
- `Application Builder`

Each system is linked to a specific documentation section via a `!docs` keyword.

The documentation folder is structured in the following way:

```
documentation
     - 01-general (associated to `VAS Platform`)
     - 02-vasCore (associated to `VAS Core Components`)
     - 03-vasApplications (associated to `VAS Applications`)
     - 04-vasInfra (associated to `VAS Infrastructure`)
     - 05-vasBuilder (associated to `Application Builder`)
```
I'd like to have the documentation presented in the same order I defined in the documentation folder. However, it is rendered in the following order (alphabetical apparently):

1. VAS Platform
2. Application Builder
3. VAS Applications
4. VAS Core Components
5. VAS Infrastructure

There is no problem with the content: just the order of the sections is not what I'd like.

**Comment by simonbrowndotje** [comment]
Can you provide a ZIP file containing a small example workspace.dsl file and documentation folder?

**Comment by simonbrowndotje** [comment]
Thanks for the example ... what you're seeing is as designed:

- "VAS Platform" is the name of the workspace, and you have documentation associated with the workspace, so this is showing up at the top.
- "Application Builder", etc are all separate software systems, each of which has documentation attached. Software systems are being rendered in the left navigation in alphabetical order, and there's no way to override this.
