### ISSUE TITLE
Disable Ctrl+Wheel zoom in any part of the UI.

### ISSUE THREAD

**Issue by fabiocarneiro** [structurizr/structurizr#85]
If I am using this behavior but I accidentally move the cursor outside of the `#diagramViewport`, then I immediately zoom the whole page (browser zoom). Applications that use `ctrl+wheel` to control zoom usually disable the browser zoom in any other part of the UI. 

You are listening to "mouse-wheel" events **only on** the element with id `#diagramVieport`. In your code:

```javascript
$('#diagramViewport').bind("mousewheel", function(event) {
    if (event.ctrlKey === true) {
        if (event.originalEvent.wheelDelta > 0) {
            Structurizr.diagram.zoomIn();
            event.preventDefault();
        } else {
            Structurizr.diagram.zoomOut();
            event.preventDefault();
        }
    }
});
```

This can be done by listening to the `mouse-wheel` event everywhere (window) and preventing the default behavior:

```javascript
$(window).bind('mousewheel', function (event) {
   if (event.ctrlKey == true) {
       event.preventDefault();
   }
});
```

or maybe just adding to your current code (not tested):

```javascript
$(window).bind("mousewheel", function(event) {
    event.preventDefault();

    if((event.target.id !== "diagramViewport") || (event.ctrlKey !== true) {
        return;
    }

    if (event.originalEvent.wheelDelta > 0) {
        Structurizr.diagram.zoomIn();
        return;
    } 
          
    Structurizr.diagram.zoomOut();
});
```

**Comment by simonbrowndotje** [comment]
Interestingly the browser zooming only happens on some web browsers, but I've added some code to essentially disable this feature.

**Comment by fabiocarneiro** [comment]
It got a lot better now, at least the browser zoom is gone. I just wanted to add that is also a bit weird that now I ctrl+scroll anywhere and it zooms the diagram viewport. I think the expected behavior would be:

* ctrl + zoom - not in the diagram viewport - nothing happens
* ctrl + zoom - in the diagram viewport - zooms the diagram viewport
