### ISSUE TITLE
Website needs to show "workspace.dsl" files for every drawn example

### ISSUE THREAD

**Issue by gmlewis** [structurizr/structurizr#88]
The website has a page dedicated to DSL "Notation": https://structurizr.com/help/notation
and shows examples, but I can't find a single example where the "workspace.dsl" file is shown.
These files should be front and center when trying to explain the DSL notation.

Here's another example about valid Shapes: https://structurizr.com/help/shapes
We see a lot of beautiful shapes but not a single line from the "workspace.dsl" file that created them.
Please fix this, as it is incredibly frustrating.

Thanks.

**Comment by simonbrowndotje** [comment]
The Structurizr diagram renderer isn't coupled to the DSL format, and workspaces can be created using a number of tools (Java, .NET, etc). If you're using the DSL, you might find the following links helpful:

 - [DSL language reference](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md) (specifically [element-style](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#element-style))
 - [DSL cookbook](https://github.com/structurizr/dsl/tree/master/docs/cookbook) (specifically [Element styles](https://github.com/structurizr/dsl/tree/master/docs/cookbook/element-styles)) 

Also, you can find some DSL examples at https://github.com/structurizr/examples/tree/main/dsl

**Comment by gmlewis** [comment]
Thank you, Simon!
