### ISSUE TITLE
Influence Diagram Sequence in Structurizr

### ISSUE THREAD

**Issue by woutervanranst** [structurizr/structurizr#92]
Hi, how is the sequence determined with which diagrams are shown in structurizr?

My hypotheses falsified:
- alphabetically by Title of the diagram (nope, see 3rd example)
- alphabetically by key (nope, see 4th example)
- by order of adding (nope, I added all the SystemContext diagrams first, then the Container diagrams)

![image](https://user-images.githubusercontent.com/6490925/175506309-c33b04f0-5a9e-40e5-a031-c2c8a1c88730.png)

**Comment by simonbrowndotje** [comment]
Which library/tool are you using to create the workspace?
