### ISSUE TITLE
Add AWS Transfer Family to theme

### ISSUE THREAD

**Issue by kharry5** [structurizr/structurizr#94]
The AWS theme is missing the Transfer Family service. Can it be added?

![Res_AWS-Transfer-Family_AWS-SFTP_48_Light](https://user-images.githubusercontent.com/188371/176830493-8148c9fa-d65e-4d05-a749-e7a5ad5c91d1.png)
![Res_AWS-Transfer-Family_AWS-SFTP_48_Light](https://user-images.githubusercontent.com/188371/176830497-0eb84c65-5acf-468b-9906-4a5d6af4a373.svg)
![Res_AWS-Transfer-Family_AWS-FTPS_48_Light](https://user-images.githubusercontent.com/188371/176830499-5f8638a7-73c8-49f6-8e64-0e6e826c058c.png)
![Res_AWS-Transfer-Family_AWS-FTPS_48_Light](https://user-images.githubusercontent.com/188371/176830501-cdd45ed6-a64b-4555-ad96-8286dd33d0e4.svg)
![Res_AWS-Transfer-Family_AWS-FTP_48_Light](https://user-images.githubusercontent.com/188371/176830502-b37842c2-9f90-405b-be1d-3c97aaecfb14.png)
![Res_AWS-Transfer-Family_AWS-FTP_48_Light](https://user-ima
![Res_AWS-Transfer-Family_AWS-FTP_48_Dark](https://user-images.githubusercontent.com/188371/176830517-f55cf761-25a3-471b-83aa-7d4e09f61776.png)
![Res_AWS-Transfer-Family_AWS-FTP_48_Dark](https://user-images.githubusercontent.com/188371/176830518-f0ebb854-1c7d-4277-aedf-3ee8244e53a9.svg)
![Res_AWS-Transfer-Family_AWS-FTPS_48_Dark](https://user-images.githubusercontent.com/188371/176830519-4ffae056-d165-4ec7-aea3-33778f9b1c64.png)
![Res_AWS-Transfer-Family_AWS-FTPS_48_Dark](https://user-images.githubusercontent.com/188371/176830520-b1fdd22b-f465-4780-adfd-a4c901b83ffe.svg)
![Res_AWS-Transfer-Family_AWS-SFTP_48_Dark](https://user-images.githubusercontent.com/188371/176830524-9b37a6f8-dda7-44d7-adc7-0a3201391d53.png)
![Res_AWS-Transfer-Family_AWS-SFTP_48_Dark](https://user-images.githubusercontent.com/188371/176830526-4502d8dc-54ed-4e3f-9598-50c54a037c12.svg)
ges.githubusercontent.com/188371/176830504-eb58c371-e8fa-4caf-850f-9433055a002f.svg)
?

**Comment by simonbrowndotje** [comment]
These are available as a part of the "20220430" theme -> https://structurizr.com/help/theme?url=https://static.structurizr.com/themes/amazon-web-services-2022.04.30/theme.json
